apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    elk-component: fb01
    app: elk
  name: fb01
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      elk-component: fb01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        elk-component: fb01
    spec:
      containers:
        - args:
            - --e
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://es01:9200
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic_creds
                  key: fb_password
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic_creds
                  key: fb_username
            - name: KIBANA_HOST
              value: http://kib01:5601
            - name: TZ
              value: America/New_York
          image: docker.elastic.co/beats/filebeat:7.10.0
          name: fb01
          ports:
            - containerPort: 9001
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              name: filebeatconfig
              subPath: filebeat.yml
            - mountPath: /usr/share/filebeat/modules.d/iptables.yml
              name: filebeatiptables
              subPath: iptables.yml
           # - mountPath: /usr/share/filebeat/modules.d/netflow.yml
           #   name: netflow
           #   subPath: netflow.yml
      restartPolicy: Always
      volumes:
        - name: filebeatconfig
          configMap:
            name: filebeatconfig
        - name: filebeatiptables
          configMap:
            name: fb-iptablesconfig
       # - name: netflow
       #   configMap:
       #     name: fb-netflowconfig
