apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: logstashparseerror
   namespace: elk
spec:
   accessModes:
      - ReadWriteMany
   storageClassName: nfs-storage
   resources:
      requests:
         storage: 2Gi

