apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    elk-component: ls01
    app: elk
  name: ls01
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      elk-component: ls01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        elk-component: ls01
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://es01:9200
            - name: LS_JAVA_OPTS
              value: -Xmx256m -Xms256m
            - name: LOGSTASH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic_creds
                  key: ls_username
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic_creds
                  key: ls_password
            - name: TZ
              value: America/New_York
          image: docker.elastic.co/logstash/logstash:7.10.0
          name: ls01
          ports:
            - containerPort: 5141
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: logstashconfig
              subPath: logstash.yml
            - mountPath: /usr/share/logstash/pipeline
              name: logstashpipeline
            - mountPath: /usr/share/logstash/patterns
              name: logstashpattern
            - mountPath: /usr/share/logstash/parseerrors
              name: logstashparseerror
      restartPolicy: Always
      volumes:
        - name: logstashconfig
          configMap:
            name: logstashconfig
        - name: logstashpipeline
          configMap:
            name: logstashpipeline
        - name: logstashpattern
          configMap:
            name: logstashpattern
        - name: logstashparseerror
          persistentVolumeClaim:
            claimName: logstashparseerror
