apiVersion: v1
kind: Service
metadata:
  name: ef01
  namespace: elk
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 172.16.1.5
  ports:
    - port: 2055
      targetPort: 2055
      protocol: UDP
      name: "netflow"
  selector:
    elk-component: ef01
  type: LoadBalancer
